version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem install bundler
      - bundle install
  build:
    commands:
      - echo Building and Deploying at `date`
      - rake build
      - echo Build completed at `date`

  post_build:
    commands:
      - echo Deploying to S3 at `date`
      - rake deploy
      - echo Deployment completed at `date`
